[MIN-64] 사용자 알림 옵션 구현
NaJuDoRyeong/mineme-server pull request #41
Opened 2023-05-09 02:28 UTC by Floodnut

## Update
- [ ] Hot Fix
- [ ] Release
- [x] Develop
- [ ] Others

## Description
* Feature #31 
* Feature #37 

## New/Edited policies
- Spring Security Filter에서 발생하는 오류를 해결했습니다.
- 사용자 알림 옵션 On/Off 기능을 구현했습니다.

2023-05-11 00:58 UTC, jujuwon requested changes
확인했습니다 !
리뷰에 대해 코멘트 주시고 다시 review 요청 부탁드릴게요 !

2023-05-11 00:58 UTC, jujuwon commented on src/main/java/com/mineme/server/common/Utils.java
> +	}
대소문자에 관련된 처리를 해주면 좋을 것 같습니다 !

2023-05-11 00:58 UTC, jujuwon commented on src/main/java/com/mineme/server/common/Utils.java
> +	}
추가로 클라이언트로부터 y, n 을 받아서 엔티티에 true, false 로 적용하게 되는데
클라이언트로 받을 때부터 boolean 값으로 받게 api 명세를 수정하고 구현하는게 어떨까요?
엔티티 필드가 boolean 이라면 불필요한 컨버팅이라고 생각됩니다 !

2023-05-11 00:58 UTC, jujuwon commented on src/main/java/com/mineme/server/entity/User.java
> +	}
매개변수 type 이 null 인 경우에 대한 검증이 앞단에서 이루어지나요 ?

2023-05-11 00:58 UTC, jujuwon commented on src/main/java/com/mineme/server/user/controller/UserController.java
> +		userServiceImpl.removeUser();
변수의 이름은 userService 로 유지하고 DI 되는 클래스만 변경하면 이후 코드의 수정은 하지 않아도 좋지 않을까 싶습니다 !

2023-05-11 14:18 UTC, Floodnut commented on src/main/java/com/mineme/server/common/Utils.java
> +	}
'y', 'n'으로 구분된 명세가 많아서 공통으로 처리하려고 어댑터 느낌으로 만들었습니다!
그런데 'n'에 대한 처리가 불명확해서 이 부분을 적어도 API 엔드포인트 쪽이라도 true/false 처리하는게 어떨까 싶어서 제안할까 싶었습니다.

추가적으로 대소문자에 대한 처리도 true/false에 대한 논의 후 반영할까 하는데 어떻게 생각하시나요?!

2023-05-11 14:24 UTC, Floodnut commented on src/main/java/com/mineme/server/entity/User.java
> +	}
앗... Null 체크에 대한 부분을 다른 곳에서 처리하고 검증된 내역만 넘기려했는데 지금 보니 빠져있네요.

이 예외에 대한 처리를 여기서 적용하겠습니다!

2023-05-11 14:25 UTC, Floodnut commented on src/main/java/com/mineme/server/user/controller/UserController.java
> +		userServiceImpl.removeUser();
넵 인터페이스는 의존성 주입의 대상이 아니어서 코드 수정할 필요가 없을 것 같습니다!
이후 인터페이스와 구현체에 상관없이 객체명을 유지하겠습니다!

2023-05-11 14:29 UTC, Floodnut commented on src/main/java/com/mineme/server/entity/User.java
> +	}
추가적으로 else에 대한 처리가 없는 이유는 Null 이외의 변조에 대해서 예외를 뿜는 것이 아닌 기존값 유지로 대응하려 했습니다.

이 부분에 대해서 명확하게 예외를 반환해서 데이터 처리에 대한 가시성을 제공할지 처리를 숨길지에 대한 의견을 주시면 감사하겠습니다!

2023-05-12 04:54 UTC, jujuwon commented on src/main/java/com/mineme/server/common/Utils.java
> +	}
음 제 개인적인 생각으로는 y, n 보다는 true/false 로 전부 boolean 타입으로 변경하는 게 좋다고 생각합니다 !
boolean 타입으로 변경하면 공수가 많이 들까요 ?
추가로 boolean 타입으로 변경하면 대소문자에 대한 처리는 무시하셔도 될듯 합니다 🙋‍♂️

2023-05-12 04:55 UTC, jujuwon commented on src/main/java/com/mineme/server/entity/User.java
> +	}
이 부분은 명확하게 예외를 반환하도록 하는 것이 클라이언트 분들이 실수로 다른 타입을 넘겨도 검증이 될 것 같아서,
테스트 단계인 지금은 에러 응답을 반환하는 게 저는 맞다고 생각합니다 !

2023-05-16 06:22 UTC, jujuwon requested changes

2023-05-16 06:22 UTC, jujuwon commented on src/main/java/com/mineme/server/entity/User.java
> +
null 체크가 메소드 가장 상위에 있어야 null exception 이 발생하지 않을 것 같습니다 !

2023-05-17 13:59 UTC, Floodnut commented on src/main/java/com/mineme/server/entity/User.java
> +
Null 체크를 변경하겠습니다!

2023-05-18 12:08 UTC, jujuwon approved these changes
좋네요~~ 고생하셨습니다 !

2023-05-18 16:03 UTC, merged